<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iiEpXiZ' shared service.

return $this->privates['.service_locator.iiEpXiZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CompteController::inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DepotController::inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController::inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UtilisateurController::register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\UtilisateurController::update' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
    'App\\Controller\\CompteController:inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\DepotController:inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\PartenaireController:inserer' => ['privates', '.service_locator.ZIsCxOI', 'get_ServiceLocator_ZIsCxOIService.php', true],
    'App\\Controller\\UtilisateurController:register' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\UtilisateurController:update' => ['privates', '.service_locator.nk9g.Cv', 'get_ServiceLocator_Nk9g_CvService.php', true],
], [
    'App\\Controller\\CompteController::inserer' => '?',
    'App\\Controller\\DepotController::inserer' => '?',
    'App\\Controller\\PartenaireController::inserer' => '?',
    'App\\Controller\\UtilisateurController::register' => '?',
    'App\\Controller\\UtilisateurController::update' => '?',
    'App\\Controller\\CompteController:inserer' => '?',
    'App\\Controller\\DepotController:inserer' => '?',
    'App\\Controller\\PartenaireController:inserer' => '?',
    'App\\Controller\\UtilisateurController:register' => '?',
    'App\\Controller\\UtilisateurController:update' => '?',
]);
