<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWGOGqkk\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWGOGqkk/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerWGOGqkk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerWGOGqkk\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerWGOGqkk\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'WGOGqkk',
    'container.build_id' => '3f93aa7b',
    'container.build_time' => 1564477009,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWGOGqkk');
