<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBOsPCnN\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBOsPCnN/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerBOsPCnN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerBOsPCnN\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerBOsPCnN\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'BOsPCnN',
    'container.build_id' => '64c7dfaf',
    'container.build_time' => 1564495823,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBOsPCnN');
