<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerESPx0xx\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerESPx0xx/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerESPx0xx.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerESPx0xx\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerESPx0xx\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ESPx0xx',
    'container.build_id' => '884bfe1c',
    'container.build_time' => 1563956563,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerESPx0xx');
