<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9ahc8rN\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9ahc8rN/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container9ahc8rN.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container9ahc8rN\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container9ahc8rN\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '9ahc8rN',
    'container.build_id' => 'dcedecec',
    'container.build_time' => 1564487126,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9ahc8rN');
